apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    appstudio.openshift.io/application: go-application-sample
    appstudio.openshift.io/component: go-component-sample
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: go-component-sample
  namespace: test
spec:
  git_provider:
    secret:
      key: github.token
      name: pipelines-as-code-secret
    webhook_secret:
      key: https___github.com_mmorhun-org_devfile-stack-go
      name: pipelines-as-code-webhooks-secret
  url: https://github.com/mmorhun-org/devfile-stack-go
